INHERIT: ../base.yml
site_name: "Документация <code>D0SL2</code>"
docs_dir: '../../docs/ru'
site_dir: '../../build/docs/ru'

theme:
  language: ru

nav:
  - Главная: 'index.md'
  - Философия:
    - philosophy/index.md
    - Почему мы создали <code>D0SL</code>: philosophy/motivation.md
    - Математика <code>D0SL</code>: philosophy/math.md
  - Начинающим:
    - getting-started/index.md
    - Настройка окружения разработчика: getting-started/dev-env.md
  - Язык D0SL:
    - language/index.md
    - Доменные модели: language/domain-models.md
  - Блог: 'blog/index.md'

plugins:
  - search:
      lang: ru
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      tags_slugify_separator: '-'
  - blog:
      blog_toc: true

copyright: Copyright &copy; 2018 - 2024 Eyeline