INHERIT: ../base.yml
site_name: "<code>D0SL2</code> Docs"
docs_dir: '../../docs/en'
site_dir: '../../build/docs/en'

theme:
  language: en

nav:
  - Home: 'index.md'
  - Philosophy:
    - philosophy/index.md
    - Why we made <code>D0SL</code>?: philosophy/motivation.md
  - Getting started with <code> D0SL</code>:
    - getting-started/index.md
    - Setting up development environment: getting-started/dev-env.md
  - Blog: 'blog/index.md'

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      tags_slugify_separator: '-'
  - blog:
      blog_toc: true

copyright: Copyright &copy; 2018 - 2024 Eyeline